### ISSUE TITLE
Run time UI errors

### ISSUE THREAD

**Issue by kinsleykajiva** [mkpaz/atlantafx#1] opened 2022-07-25 11:54 UTC
hi, so I have cloned the repo to test but I am getting this view as I have attached the image. 

yes I did run npm install and also resolved all java maven dependencies .

jdk liberica-18.0.1.1

![image](https://user-images.githubusercontent.com/8996252/180772019-d269ec31-3f9e-4ca9-b21b-9fad129eecdd.png)

**Comment by mkpaz** [comment] 2022-07-25 12:35
I suppose this is caused by incorrect CSS compilation. Looks like your CSS file still contains SASS color variables `-color-*`. Are you by chance use global NodeJS? If so, you shouldn't do this, as it will be installed locally via `maven-frontend-plugin`. I'm not yet posted build instructions, which include e.g. things like hot reload, but you can find out how it works from the [github workflow](https://github.com/mkpaz/atlantafx/blob/62f94c6a2cba71a9fd6111ec59f9962249331ad7/.github/workflows/tagged-release.yml#L30).

**Comment by mkpaz** [comment] 2022-07-25 16:29
I added build instructions.

**Comment by mkpaz** [comment] 2022-08-02 09:20
Resolved by https://github.com/mkpaz/atlantafx/pull/2.

**Closed by mkpaz** 2022-08-02 09:20 UTC
